name: twirp_dart_core
description: Core library for using Twirp + Dart
version: 1.0.0+2
homepage: https://github.com/apptreesoftware/twirp_dart_core
author: Matthew Smith<matthew.smith@apptreesoftware.com>

environment:
  sdk: ">=1.20.1 <3.0.0"

dependencies:
